import { CourseItem } from '../../features/courses/courses.component';

export const KIDS_COURSES_DATA: CourseItem[] = [
  // =========================================================================
  // TRACK 1: EXPLORER TRACK (AGES 6–8)
  // =========================================================================
  {
    id: 'digital-explorer-6-8',
    code: 'EXP01',
    category: 'kids',
    kidsAgeCategory: '6-8',
    titleEn: 'Digital Explorer: Digital Literacy & Logic',
    titleAr: 'مكتشف الرقميات: التفكير المنطقي والمهارات الرقمية',
    descEn: 'Build digital literacy, computer hardware awareness, keyboard/mouse mastery, pattern recognition, and basic algorithms through interactive stories and visual puzzles.',
    descAr: 'بناء المهارات الرقمية الأساسية، التعرف على مكونات الحاسوب، استخدام الفأرة ولوحة المفاتيح، والتعرف على الأنماط والخوارزميات عبر الألعاب والقصص التفاعلية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'No prior experience required. Age 6–8.',
    prerequisiteAr: 'لا يتطلب معرفة سابقة. للأعمار من 6 إلى 8 سنوات.',
    levelEn: 'Beginner (Explorer 1/4)',
    levelAr: 'مبتدئ (مسار المكتشف 1/4)',
    ageBadgeEn: 'Ages 6–8',
    ageBadgeAr: 'من 6 إلى 8 سنوات',
    topics: ['Computer Parts & File Safety', 'Mouse & Keyboard Mastery', 'Pattern Recognition & Sequences', 'Unplugged Algorithms', 'Loops & Simple Conditions'],
    projectsEn: ['Digital Detective Activity', 'Build a Computer Puzzle', 'File Treasure Hunt', 'My Digital Storybook', 'Pattern Puzzle Game', 'Dance Loop Animation', 'My First Digital World'],
    projectsAr: ['نشاط المحقق الرقمي Digital Detective', 'تركيب أجزاء الحاسوب Build a Computer', 'صندوق الكنز الرقمي للطفل', 'قصتي الرقمية الأولى My Digital Story', 'لعبة ألغاز الأنماط Pattern Puzzle', 'مشروع تحريك رقصة الشخصية Dance Loop', 'عالمي الرقمي الأول My Digital World'],
    syllabusModulesEn: [
      {
        moduleTitleEn: 'Module 1: Technology & Computer Orientation',
        moduleTitleAr: 'الوحدة 1: التعرف على الحاسوب والتكنولوجيا من حولنا',
        sessionsRangeEn: 'Sessions 1–4 (8 Hours)',
        sessionsRangeAr: 'الجلسات 1–4 (8 ساعات)',
        topicsEn: [
          'Session 1: Technology Around Us & Safe Usage (Digital Detective).',
          'Session 2: Computer Hardware Parts & Functions (Build a Computer).',
          'Session 3: Mouse, Keyboard & File Management (File Treasure Hunt).',
          'Session 4: Images, Sound & Video Creation (My Digital Story).'
        ],
        topicsAr: [
          'الجلسة 1: التكنولوجيا من حولنا والسلامة الرقمية (نشاط المحقق الرقمي).',
          'الجلسة 2: أجزاء الحاسوب ومكوناته الأساسية (لعبة تركيب الحاسوب).',
          'الجلسة 3: إتقان الفأرة ولوحة المفاتيح وإدارة الملفات (البحث عن الكنز الرقمي).',
          'الجلسة 4: التعامل مع الصور والأصوات والفيديو (إنشاء قصتي الرقمية الأولى).'
        ]
      },
      {
        moduleTitleEn: 'Module 2: Algorithmic Logic & Debugging',
        moduleTitleAr: 'الوحدة 2: التفكير الخوارزمي وحل المشكلات',
        sessionsRangeEn: 'Sessions 5–8 (8 Hours)',
        sessionsRangeAr: 'الجلسات 5–8 (8 ساعات)',
        topicsEn: [
          'Session 5: Patterns & Sequences in Daily Life.',
          'Session 6: Algorithms Without Code (Robot Instructions Unplugged).',
          'Session 7: Loops & Repetition (Dance Loop Animation).',
          'Session 8: Conditions & Decisions (If / Then Choice Game).'
        ],
        topicsAr: [
          'الجلسة 5: الأنماط والتسلسلات Logic Patterns في الحياة اليومية.',
          'الجلسة 6: الخوارزميات بدون كود (إعطاء التعليمات للروبوت).',
          'الجلسة 7: الحلقات التكرارية Loops (حركة الشخصية المتكررة).',
          'الجلسة 8: الشروط والقرارات (لعبة الإجابة Conditional Game).'
        ]
      },
      {
        moduleTitleEn: 'Module 3: Creative Character Design & Capstone',
        moduleTitleAr: 'الوحدة 3: التصميم الإبداعي ومعرض المشروع النهائي',
        sessionsRangeEn: 'Sessions 9–12 (8 Hours)',
        sessionsRangeAr: 'الجلسات 9–12 (8 ساعات)',
        topicsEn: [
          'Session 9: Debugging & Experimentation (Fix the Broken Robot).',
          'Session 10: Digital Character Design & Drawing Colors.',
          'Session 11: Project Sprint: Building "My Digital World".',
          'Session 12: Final Demo Day & Presentation to Parents.'
        ],
        topicsAr: [
          'الجلسة 9: اكتشاف ومعالجة الأخطاء (إصلاح الروبوت المكسور).',
          'الجلسة 10: تصميم الشخصيات الرسم التفاعلي الألوان الرقمية.',
          'الجلسة 11: ورشة عمل المشروع: بناء مشروع عالمي الرقمي.',
          'الجلسة 12: يوم العروض التقديمية النهائي والحصول على الشهادة.'
        ]
      }
    ],
    completionStandardEn: 'Complete 8 micro-activities, submit 2 final digital projects, and present the work at Demo Day.',
    completionStandardAr: 'إكمال 8 أنشطة مصغرة، تسليم مشروعين نهائيين، وتقديم العرض التفاعلي في يوم العروض Demo Day.'
  },
  {
    id: 'scratch-jr-creator-6-8',
    code: 'EXP02',
    category: 'kids',
    kidsAgeCategory: '6-8',
    titleEn: 'ScratchJr Creator: Visual Coding & Stories',
    titleAr: 'مبدع ScratchJr: البرمجة المرئية والقصص التفاعلية',
    descEn: 'Learn ScratchJr visual programming blocks, multi-character scenes, motion controls, sound recordings, and interactive storytelling.',
    descAr: 'تعلم رموز البرمجة البصرية في ScratchJr، إدارة المشاهد والشخصيات المتعددة، حركة العناصر، الأصوات والقصص التفاعلية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of EXP01 or basic digital literacy. Age 6–8.',
    prerequisiteAr: 'إتمام كورس EXP01 أو المعرفة الرقمية البسيطة. للأعمار من 6 إلى 8 سنوات.',
    levelEn: 'Beginner (Explorer 2/4)',
    levelAr: 'مبتدئ (مسار المكتشف 2/4)',
    ageBadgeEn: 'Ages 6–8',
    ageBadgeAr: 'من 6 إلى 8 سنوات',
    topics: ['ScratchJr Interface & Characters', 'Motion Blocks & Grid Coordinates', 'Events & Trigger Blocks', 'Speech Bubbles & Voice Recording', 'Multi-Scene Storytelling'],
    projectsEn: ['Dancing Character Animation', 'Animal Race Game', 'Space Trip Adventure', 'Interactive Fairy Tale Story', 'Catch the Falling Star Game'],
    projectsAr: ['حركة الشخصية الراجلة Dancing Character', 'لعبة سباق الحيوانات Animal Race', 'مغامرة رحلة الفضاء Space Trip', 'قصة الأسطورة التفاعلية Interactive Story', 'لعبة التقاط النجمة Catch the Star'],
    syllabusModulesEn: [
      {
        moduleTitleEn: 'Module 1: Characters, Motion & Sound',
        moduleTitleAr: 'الوحدة 1: الشخصيات والحركة والأصوات',
        sessionsRangeEn: 'Sessions 1–4 (8 Hours)',
        sessionsRangeAr: 'الجلسات 1–4 (8 ساعات)',
        topicsEn: [
          'Session 1: ScratchJr Interface, Adding Characters & Custom Backdrops.',
          'Session 2: Motion Blocks, Direction, Distance & Speed Control.',
          'Session 3: Sound Blocks, Custom Voice Recordings & Sound Effects.',
          'Session 4: Project 1: Building a Dancing Character Show.'
        ],
        topicsAr: [
          'الجلسة 1: واجهة ScratchJr، إضافة الشخصيات والخلفيات الخاصة.',
          'الجلسة 2: حزمة حركة العناصر، الاتجاهات، مسافة الحركة والتسريع.',
          'الجلسة 3: حزمة الأصوات، تسجيل الصوت الخاص وتأثيرات الصوت.',
          'الجلسة 4: مشروع 1: تصميم استعراض الشخصية الضاحكة.'
        ]
      },
      {
        moduleTitleEn: 'Module 2: Events & Multi-Scene Storytelling',
        moduleTitleAr: 'الوحدة 2: الأحداث والانتقال بين المشاهد',
        sessionsRangeEn: 'Sessions 5–8 (8 Hours)',
        sessionsRangeAr: 'الجلسات 5–8 (8 ساعات)',
        topicsEn: [
          'Session 5: Start Events (Green Flag, Tap Character, Bump Collision).',
          'Session 6: Message Sending & Receiving Between Characters.',
          'Session 7: Creating Multi-Scene Books & Scene Navigation.',
          'Session 8: Project 2: Interactive Animal Race & Space Trip Story.'
        ],
        topicsAr: [
          'الجلسة 5: أحداث البداية (العلم الأخضر، النقر على الشخصية، والاصطدام).',
          'الجلسة 6: إرسال واستقبال الرسائل التفاعلية بين الشخصيات.',
          'الجلسة 7: إنشاء القصص متعددة المشاهد والتنقل بين الصفحات.',
          'الجلسة 8: مشروع 2: لعبة سباق الحيوانات ومغامرة الفضاء.'
        ]
      },
      {
        moduleTitleEn: 'Module 3: Game Mechanics & Capstone',
        moduleTitleAr: 'الوحدة 3: آليات الألعاب ومشروع التخرج',
        sessionsRangeEn: 'Sessions 9–12 (8 Hours)',
        sessionsRangeAr: 'الجلسات 9–12 (8 ساعات)',
        topicsEn: [
          'Session 9: Repeat Blocks, Forever Loops & Timing.',
          'Session 10: Designing Game Victory & Retry Mechanics.',
          'Session 11: Capstone Project: Catch the Falling Star Game.',
          'Session 12: Parent Demo & Graduation Certification.'
        ],
        topicsAr: [
          'الجلسة 9: التكرار المحدد، التكرار المستمر والتوقيت.',
          'الجلسة 10: تصميم شروط الفوز وإعادة المحاولة في اللعبة.',
          'الجلسة 11: مشروع التخرج: لعبة صيد النجوم الساقطة.',
          'الجلسة 12: العرض التقديمي النهائي وحفل تخرج المكتشف الصغير.'
        ]
      }
    ],
    completionStandardEn: 'Create 5 distinct ScratchJr animated games and present a working multi-scene story project.',
    completionStandardAr: 'إنشاء 5 ألعاب وقصص تفاعلية بـ ScratchJr وتقديم عرض متحرك متعدد المشاهد.'
  },
  {
    id: 'scratch-storyteller-6-8',
    code: 'EXP03',
    category: 'kids',
    kidsAgeCategory: '6-8',
    titleEn: 'Scratch Storyteller: Animation & Variables',
    titleAr: 'حكاواتي Scratch 3.0: التحريك والقصص المتطورة',
    descEn: 'Transition to Scratch 3.0 desktop, learn sprites, backdrops, broadcast messages, simple variables, score counting, and interactive maze games.',
    descAr: 'الانتقال إلى Scratch 3.0 الرئيسي، تعلم إدارة الكائنات Sprites، الرسائل التفاعلية Broadcast، المتغيرات البسيطة، النقاط ولعبة المتاهة.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of EXP02 or visual coding basics. Age 6–8.',
    prerequisiteAr: 'إتمام كورس EXP02 أو أساسيات البرمجة البصرية. للأعمار من 6 إلى 8 سنوات.',
    levelEn: 'Intermediate (Explorer 3/4)',
    levelAr: 'متوسط (مسار المكتشف 3/4)',
    ageBadgeEn: 'Ages 6–8',
    ageBadgeAr: 'من 6 إلى 8 سنوات',
    topics: ['Scratch 3.0 Interface & Costume Editor', 'Broadcast Messages & Events', 'Variables for Score & Lives', 'If-Then Conditional Logic', 'Sensing & Maze Physics'],
    projectsEn: ['Animated Greeting Card', 'Interactive Cartoon Story', 'Maze Runner Adventure Game', 'Math Quiz Magic Game'],
    projectsAr: ['بطاقة تهنئة متحركة Interactive Card', 'قصة كرتونية تفاعلية Cartoon Story', 'لعبة بطل المتاهة Maze Runner', 'لعبة الرياضيات السحرية Quiz Magic'],
    completionStandardEn: 'Build an interactive story and a working maze game with score variables in Scratch 3.0.',
    completionStandardAr: 'بناء قصة تفاعلية ولعبة متاهة مكتملة مع عداد النقاط بـ Scratch 3.0.'
  },
  {
    id: 'game-maker-6-8',
    code: 'EXP04',
    category: 'kids',
    kidsAgeCategory: '6-8',
    titleEn: 'Game Maker: 2D Arcade & Game Design',
    titleAr: 'صانع الألعاب: برمجة ألعاب الأركيد 2D',
    descEn: 'Learn game design rules, win/lose logic, multiple levels, player lives, scoreboards, and bug fixing in Scratch 3.0 arcade games.',
    descAr: 'تعلم قواعد تصميم الألعاب، شروط الفوز والخسارة، المستويات المتعددة، عداد الأرواح، النقاط وإصلاح الأخطاء في ألعاب الأركيد.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of EXP03 or Scratch basics. Age 6–8.',
    prerequisiteAr: 'إتمام كورس EXP03 أو أساسيات Scratch. للأعمار من 6 إلى 8 سنوات.',
    levelEn: 'Advanced (Explorer 4/4)',
    levelAr: 'متقدم (مسار المكتشف 4/4)',
    ageBadgeEn: 'Ages 6–8',
    ageBadgeAr: 'من 6 إلى 8 سنوات',
    topics: ['Game Physics & Gravity Simulation', 'Win / Game Over Screens', 'Multi-Level Progression', 'Score & Highscore Variables', 'Game Sound Effects & Testing'],
    projectsEn: ['Space Shooter Arcade Game', 'Platformer Adventure Game', 'Fruit Catcher Challenge', 'Quiz Adventure Game'],
    projectsAr: ['لعبة معركة الفضاء Space Shooter', 'لعبة القفز المنصي Platformer', 'لعبة التقاط الفواكه Fruit Catcher', 'مغامرة الاختبارات Quiz Adventure'],
    completionStandardEn: 'Publish a multi-level 2D Arcade Game with complete win/lose logic and sound effects.',
    completionStandardAr: 'نشر لعبة أركيد ثنائية الأبعاد بمستويات متعددة وشاشات الفوز والخسارة والتأثيرات الصوتية.'
  },

  // =========================================================================
  // TRACK 2: CREATOR TRACK (AGES 9–11)
  // =========================================================================
  {
    id: 'scratch-game-studio-9-11',
    code: 'CRE01',
    category: 'kids',
    kidsAgeCategory: '9-11',
    titleEn: 'Scratch Game Studio: Advanced 2D Physics',
    titleAr: 'استوديو ألعاب Scratch 3.0: فيزياء الألعاب المتقدمة',
    descEn: 'Master complex 2D game logic, custom blocks (functions), clones, collision detection, game physics, and highscore leaderboards.',
    descAr: 'احتراف منطق الألعاب ثنائية الأبعاد، البلوكات الخاصة (الدوال)، الاستنساخ Clones، كشف الاصطدام، وفيزياء الألعاب.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'No prior experience required for Age 9–11, or Scratch foundation.',
    prerequisiteAr: 'لا يتطلب معرفة سابقة للأعمار من 9 إلى 11 سنة.',
    levelEn: 'Beginner → Intermediate (Creator 1/4)',
    levelAr: 'مبتدئ ← متوسط (مسار المبدع 1/4)',
    ageBadgeEn: 'Ages 9–11',
    ageBadgeAr: 'من 9 إلى 11 سنة',
    topics: ['Custom My Blocks (Functions)', 'Sprite Clones & Projectiles', 'Collision Detection & Boundaries', 'Global Variables & Game States', 'Level Balancing & Highscores'],
    projectsEn: ['Turbo Racing Game', 'Physics Platformer Adventure', 'Galaxy Defender Space Shooter', 'Endless Runner Game'],
    projectsAr: ['لعبة السباق السريع Turbo Racing', 'مغامرة القفز الفيزيائي Platformer', 'لعبة المدافع المجري Space Shooter', 'لعبة الجري اللانهائي Endless Runner'],
    syllabusModulesEn: [
      {
        moduleTitleEn: 'Module 1: Game Loops, Physics & Movement',
        moduleTitleAr: 'الوحدة 1: حلقات اللعبة والفيزياء والحركة',
        sessionsRangeEn: 'Sessions 1–4 (8 Hours)',
        sessionsRangeAr: 'الجلسات 1–4 (8 ساعات)',
        topicsEn: [
          'Session 1: Scratch 3.0 Advanced Setup, Motion Math & Smooth Controls.',
          'Session 2: Gravity Simulation, Jumping Mechanics & Boundary Walls.',
          'Session 3: Collision Detection (Touching Color / Touching Sprite).',
          'Session 4: Project 1: Building a Physics-Based Platformer Game.'
        ],
        topicsAr: [
          'الجلسة 1: إعداد Scratch المتقدم، الرياضيات الحركية والتحكم السلس.',
          'الجلسة 2: محاكاة الجاذبية، ميكانيكية القفز وجدران الحدود.',
          'الجلسة 3: كشف الاصطدام (ملامسة الألوان والـ Sprites).',
          'الجلسة 4: مشروع 1: بناء لعبة القفز المنصي بالفيزياء.'
        ]
      },
      {
        moduleTitleEn: 'Module 2: Clones, Custom Functions & Enemies',
        moduleTitleAr: 'الوحدة 2: الاستنساخ والدوال الخاصة والأعداء',
        sessionsRangeEn: 'Sessions 5–8 (8 Hours)',
        sessionsRangeAr: 'الجلسات 5–8 (8 ساعات)',
        topicsEn: [
          'Session 5: Sprite Cloning (Creating Waves of Enemies/Bullets).',
          'Session 6: Custom My Blocks (Functions & Reusable Code Blocks).',
          'Session 7: Health Bars, Lives Counter & Power-Up Drops.',
          'Session 8: Project 2: Galaxy Defender Space Shooter Game.'
        ],
        topicsAr: [
          'الجلسة 5: استنساخ الكائنات Clones (إنشاء موجات الأعداء والطلقات).',
          'الجلسة 6: البلوكات الخاصة My Blocks (الدوال وإعادة استخدام الأكواد).',
          'الجلسة 7: شريط الصحة Health Bar، عداد الأرواح والجوائز التفاعلية.',
          'الجلسة 8: مشروع 2: لعبة المدافع المجري الفضائية.'
        ]
      },
      {
        moduleTitleEn: 'Module 3: Game States, Leaderboards & Capstone',
        moduleTitleAr: 'الوحدة 3: حالات اللعبة المتعددة ومشروع التخرج',
        sessionsRangeEn: 'Sessions 9–12 (8 Hours)',
        sessionsRangeAr: 'الجلسات 9–12 (8 ساعات)',
        topicsEn: [
          'Session 9: Broadcast Game States (Start Menu, Game Over, Win).',
          'Session 10: Saving Highscores & Timer Calculations.',
          'Session 11: Capstone Sprint: Building Endless Runner or Racing Game.',
          'Session 12: Final Demo Day & Parent Project Presentation.'
        ],
        topicsAr: [
          'الجلسة 9: إرسال الرسائل لبناء حالات اللعبة (القائمة الرئيسية، الخسارة، الفوز).',
          'الجلسة 10: حفظ أعلى نتيجة Highscore وحساب الوقت والتحدي.',
          'الجلسة 11: ورشة مشروع التخرج: بناء لعبة الجري اللانهائي أو السباق.',
          'الجلسة 12: يوم العروض التقديمية وحفل توزيع الجوائز والشهادات.'
        ]
      }
    ],
    completionStandardEn: 'Submit 4 functional Scratch 2D games to GitHub/Scratch Studio with custom blocks and cloning mechanics.',
    completionStandardAr: 'تسليم 4 ألعاب تفاعلية بـ Scratch متضمنة البلوكات الخاصة والاستنساخ.'
  },
  {
    id: 'creative-app-builder-9-11',
    code: 'CRE02',
    category: 'kids',
    kidsAgeCategory: '9-11',
    titleEn: 'Creative App Builder: Mobile Apps (MIT App Inventor)',
    titleAr: 'مبدع التطبيقات: تطوير تطبيقات الموبايل (App Inventor)',
    descEn: 'Design real Android mobile apps using MIT App Inventor: screens, buttons, touch sensors, speech recognizer, camera, and local databases.',
    descAr: 'تصميم تطبيقات موبايل حقيقية بـ MIT App Inventor: الشاشات، الحساسات اللمسية، التعرف على الصوت، الكاميرا والقواعد المحلية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of CRE01 or basic logical thinking. Age 9–11.',
    prerequisiteAr: 'إتمام كورس CRE01 أو التفكير المنطقي البسيط. للأعمار من 9 إلى 11 سنة.',
    levelEn: 'Intermediate (Creator 2/4)',
    levelAr: 'متوسط (مسار المبدع 2/4)',
    ageBadgeEn: 'Ages 9–11',
    ageBadgeAr: 'من 9 إلى 11 سنة',
    topics: ['App Layouts & UI Components', 'Event Handlers & Touch Listeners', 'Text-to-Speech & Speech Recognizer', 'TinyDB Local Storage', 'Mobile Camera & Sound Sensors'],
    projectsEn: ['Habit Tracker Mobile App', 'Interactive Quiz App', 'Smart Flash Cards App', 'Calculator App', 'Voice Assistant Mini App'],
    projectsAr: ['تطبيق متابعة العادات Habit Tracker', 'تطبيق الاختبارات التفاعلي للموبايل', 'تطبيق البطاقات الذكية Flash Cards', 'تطبيق الحاسبة التفاعلية Calculator', 'المساعد الصوتي الصغير Voice Assistant'],
    completionStandardEn: 'Build 4 working Android mobile applications and test them on mobile devices.',
    completionStandardAr: 'تطوير 4 تطبيقات موبايل حقيقية واختبارها على الأجهزة الذكية.'
  },
  {
    id: 'web-explorer-9-11',
    code: 'CRE03',
    category: 'kids',
    kidsAgeCategory: '9-11',
    titleEn: 'Web Explorer: HTML5 & CSS3 Web Creation',
    titleAr: 'مستكشف الويب: تصميم مواقع الويب بـ HTML5 و CSS3',
    descEn: 'Learn text-based web development: HTML tags, page structure, CSS colors, fonts, margins, flexbox cards, and building a personal website portfolio.',
    descAr: 'تعلم برمجة الويب النصية: وسم HTML، هيكلة الصفحات، ألوان وخطوط CSS، نمط الصندوق، وبناء بورتفوليو موقع شخصي.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of CRE02 or basic computer typing skills. Age 9–11.',
    prerequisiteAr: 'إتمام كورس CRE02 أو المهارات الأساسية للكتابة. للأعمار من 9 إلى 11 سنة.',
    levelEn: 'Intermediate (Creator 3/4)',
    levelAr: 'متوسط (مسار المبدع 3/4)',
    ageBadgeEn: 'Ages 9–11',
    ageBadgeAr: 'من 9 إلى 11 سنة',
    topics: ['HTML Headings, Paragraphs & Links', 'Images, Videos & Tables', 'CSS Colors, Fonts & Box Model', 'Flexbox Card Layouts', 'Web Publishing Foundations'],
    projectsEn: ['Personal Profile Page', 'School Club Website', 'Game Landing Page', 'Young Inventor Portfolio'],
    projectsAr: ['صفحة التعريف الشخصية Personal Page', 'موقع النادي المدرسي School Club', 'صفحة هبوط الألعاب Game Landing Page', 'بورتفوليو المخترع الصغير Portfolio'],
    completionStandardEn: 'Design and publish a multi-page responsive personal website with HTML and CSS.',
    completionStandardAr: 'تصميم ونشر موقع ويب متكامل متعدد الصفحات باستخدام HTML و CSS.'
  },
  {
    id: 'young-game-ai-9-11',
    code: 'CRE04',
    category: 'kids',
    kidsAgeCategory: '9-11',
    titleEn: 'Young Game & AI Creator: AI Concepts & Ethics',
    titleAr: 'مبدع الألعاب والذكاء الاصطناعي الصغير',
    descEn: 'Explore how Artificial Intelligence works through pattern recognition, training data models, image classification, safe AI tools, and AI-themed games.',
    descAr: 'استكشاف كيفية عمل الذكاء الاصطناعي عبر التعرف على الأنماط، نماذج البيانات، تصنيف الصور، الأدوات الآمنة، والألعاب الذكية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of CRE03 or CRE01. Age 9–11.',
    prerequisiteAr: 'إتمام كورس CRE03 أو CRE01. للأعمار من 9 إلى 11 سنة.',
    levelEn: 'Advanced (Creator 4/4)',
    levelAr: 'متقدم (مسار المبدع 4/4)',
    ageBadgeEn: 'Ages 9–11',
    ageBadgeAr: 'من 9 إلى 11 سنة',
    topics: ['What is AI vs Traditional Code', 'Pattern Recognition & Dataset Training', 'Machine Learning Classification', 'Child-Safe AI Tools & Privacy', 'AI Game Design'],
    projectsEn: ['Smart AI Quiz Game', 'AI-Themed Interactive Story', 'Image Recognizer Demonstration', 'Interactive AI Learning Game'],
    projectsAr: ['لعبة الاختبار الذكية Smart AI Quiz', 'قصة تفاعلية حول الذكاء الاصطناعي', 'نموذج التعرف على الصور Image Recognizer', 'لعبة التعلم التفاعلية بالذكاء الاصطناعي'],
    completionStandardEn: 'Build an AI-assisted game project and present how machine learning patterns work to peers.',
    completionStandardAr: 'بناء مشروع لعبة معززة بالذكاء الاصطناعي وتقديم شرح طريقة عمل نماذج التعلم.'
  },

  // =========================================================================
  // TRACK 3: BUILDER TRACK (AGES 12–14)
  // =========================================================================
  {
    id: 'python-foundations-12-14',
    code: 'BLD01',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'Python Foundations: Text-Based Programming',
    titleAr: 'أساسيات لغة Python: البرمجة النصية الحقيقية',
    descEn: 'Learn real text-based programming syntax in Python 3: variables, data types, inputs, arithmetic, boolean logic, conditionals, and control loops.',
    descAr: 'تعلم كتابة الكود النصي الحقيقي بلغة Python 3: المتغيرات، أنواع البيانات، الإدخال، التعبير الشرطي، والحلقات التكرارية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'No prior coding experience required for Age 12–14.',
    prerequisiteAr: 'لا يتطلب معرفة سابقة للأعمار من 12 إلى 14 سنة.',
    levelEn: 'Beginner → Intermediate (Builder 1/4)',
    levelAr: 'مبتدئ ← متوسط (مسار الباني 1/4)',
    ageBadgeEn: 'Ages 12–14',
    ageBadgeAr: 'من 12 إلى 14 سنة',
    topics: ['Python Environment & VS Code', 'Variables, Strings & Data Types', 'User Input & Type Casting', 'Conditionals (if/elif/else)', 'For & While Loops'],
    projectsEn: ['Interactive Text Story Generator', 'Smart Calculator', 'Number Logic Challenge Lab', 'Decision Tree Quiz Engine'],
    projectsAr: ['مولد القصص النصية التفاعلي Story Generator', 'الحاسبة الذكية Smart Calculator', 'مختبر ألعاب التحدي الرقمي', 'محرك الأسئلة والقرارات Quiz Engine'],
    syllabusModulesEn: [
      {
        moduleTitleEn: 'Module 1: Python Environment & Data Types',
        moduleTitleAr: 'الوحدة 1: بيئة Python وأنواع البيانات الأساسية',
        sessionsRangeEn: 'Sessions 1–4 (8 Hours)',
        sessionsRangeAr: 'الجلسات 1–4 (8 ساعات)',
        topicsEn: [
          'Session 1: Python setup, VS Code IDE, print statement & syntax rules.',
          'Session 2: Variables, strings, integers, floats & basic string operations.',
          'Session 3: User input(), type conversion (int, float, str) & arithmetic.',
          'Session 4: Project 1: Building a Smart Interactive Calculator.'
        ],
        topicsAr: [
          'الجلسة 1: إعداد بيئة Python، محرر VS Code، طباعة النتائج وقواعد الأكواد.',
          'الجلسة 2: المتغيرات، النصوص، الأرقام الصحيحة والعشرية والعمليات النصية.',
          'الجلسة 3: استقبال الإدخال من المستخدم input() وتحويل أنواع البيانات.',
          'الجلسة 4: مشروع 1: بناء تطبيق الحاسبة التفاعلية الذكية.'
        ]
      },
      {
        moduleTitleEn: 'Module 2: Decision Making & Logic Control',
        moduleTitleAr: 'الوحدة 2: اتخاذ القرارات والمنطق البرمجي',
        sessionsRangeEn: 'Sessions 5–8 (8 Hours)',
        sessionsRangeAr: 'الجلسات 5–8 (8 ساعات)',
        topicsEn: [
          'Session 5: Comparison operators, Boolean logic (True/False, and, or, not).',
          'Session 6: Conditional statements: if, elif, else & nested decision trees.',
          'Session 7: For loops, range() function & string iteration.',
          'Session 8: Project 2: Interactive Text-Based Story Game.'
        ],
        topicsAr: [
          'الجلسة 5: عمليات المقارنة، المنطق البولياني (True/False والعمليات المركبة).',
          'الجلسة 6: التعبير الشرطي: if, elif, else وشجرات القرارات المتداخلة.',
          'الجلسة 7: الحلقات التكرارية for ودالة range والتكرار على النصوص.',
          'الجلسة 8: مشروع 2: لعبة القصة النصية التفاعلية.'
        ]
      },
      {
        moduleTitleEn: 'Module 3: Loops, Debugging & Capstone',
        moduleTitleAr: 'الوحدة 3: الحلقات التكرارية ومعالجة الأخطاء ومشروع التخرج',
        sessionsRangeEn: 'Sessions 9–12 (8 Hours)',
        sessionsRangeAr: 'الجلسات 9–12 (8 ساعات)',
        topicsEn: [
          'Session 9: While loops, break, continue & infinite loop safety.',
          'Session 10: Code debugging, SyntaxError vs ValueError & error handling.',
          'Session 11: Capstone Sprint: Building a Decision-Tree Quiz Engine.',
          'Session 12: Final Demo & Code Defense Presentation.'
        ],
        topicsAr: [
          'الجلسة 9: حلقات while الشرطية، أوامر break و continue والأمان.',
          'الجلسة 10: معالجة الأخطاء البرمجية SyntaxError و ValueError والتعقب.',
          'الجلسة 11: ورشة مشروع التخرج: محرك الأسئلة والقرارات الشامل.',
          'الجلسة 12: العرض التقديمي ومناقشة الكود مع أولياء الأمور.'
        ]
      }
    ],
    completionStandardEn: 'Write clean Python code without syntax errors and submit 2 working console projects to GitHub.',
    completionStandardAr: 'كتابة أكواد بايثون نصية سليمة دون أخطاء وتسليم مشروعين تفاعليين على GitHub.'
  },
  {
    id: 'python-problem-solving-12-14',
    code: 'BLD02',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'Python Problem Solving: Lists, Functions & Files',
    titleAr: 'حل المشكلات بـ Python: القوائم، الدوال والملفات',
    descEn: 'Master Python lists, dictionaries, custom functions, modules, file I/O operations, random module, and basic algorithmic problem solving.',
    descAr: 'احتراف القوائم Lists، الكائنات Dictionaries، الدوال الخاصة Functions، التعامل مع الملفات، الحزم، وحل التحديات الخوارزمية.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of BLD01 or Python fundamentals. Age 12–14.',
    prerequisiteAr: 'إتمام كورس BLD01 أو أساسيات لغة بايثون. للأعمار من 12 إلى 14 سنة.',
    levelEn: 'Intermediate (Builder 2/4)',
    levelAr: 'متوسط (مسار الباني 2/4)',
    ageBadgeEn: 'Ages 12–14',
    ageBadgeAr: 'من 12 إلى 14 سنة',
    topics: ['Python Lists & Methods', 'Dictionaries & Key-Value Pair Data', 'Functions & Parameters', 'File I/O (Read/Write txt/csv)', 'Algorithms (Search & Sort Concept)'],
    projectsEn: ['Secure Password Generator', 'Interactive Quiz Engine', 'Number Guessing AI Game', 'Text Adventure RPG Game', 'Personal Expense Tracker CLI'],
    projectsAr: ['مولد كلمة السر الآمن Password Generator', 'محرك الاختبارات Quiz Engine', 'لعبة التخمين الذكي Number Guessing', 'لعبة المغامرة النصية RPG Game', 'تطبيق تتبع المصروفات CLI'],
    completionStandardEn: 'Develop 5 functional Python programs utilizing functions, lists, and file persistence.',
    completionStandardAr: 'تطوير 5 برامج بلغة بايثون تعتمد على الدوال والقوائم وحفظ البيانات في ملفات.'
  },
  {
    id: 'web-builder-12-14',
    code: 'BLD03',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'Web Builder: HTML5, CSS Flexbox & JavaScript',
    titleAr: 'باني الويب: تصميم وبرمجة مواقع الويب التفاعلية',
    descEn: 'Build modern responsive websites using HTML5, CSS Flexbox, Grid, and JavaScript ES6+ for dynamic DOM interactions.',
    descAr: 'بناء مواقع ويب متجاوبة حديثة باستخدام HTML5، CSS Flexbox & Grid، وجافاسكريبت للتحكم التفاعلي بالـ DOM.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of BLD02 or basic programming logic. Age 12–14.',
    prerequisiteAr: 'إتمام كورس BLD02 أو المنطق البرمجي الأساسي. للأعمار من 12 إلى 14 سنة.',
    levelEn: 'Intermediate (Builder 3/4)',
    levelAr: 'متوسط (مسار الباني 3/4)',
    ageBadgeEn: 'Ages 12–14',
    ageBadgeAr: 'من 12 إلى 14 سنة',
    topics: ['Semantic HTML5 & Accessibility', 'CSS Box Model, Flexbox & Grid', 'JavaScript Basics & Variables', 'DOM Events & Click Handlers', 'Responsive Breakpoints'],
    projectsEn: ['Personal Portfolio Website', 'Academy School Website', 'Product Landing Page', 'Interactive Dynamic Quiz Web App'],
    projectsAr: ['معرض الأعمال الشخصي Portfolio', 'موقع المدرسة الأكاديمي School Website', 'صفحة هبوط المنتج Landing Page', 'تطبيق الاختبارات التفاعلي بـ JS'],
    completionStandardEn: 'Deploy a multi-page interactive web application to Netlify or GitHub Pages.',
    completionStandardAr: 'نشر تطبيق ويب تفاعلي متعدد الصفحات على Netlify أو GitHub Pages.'
  },
  {
    id: 'ai-robotics-explorer-12-14',
    code: 'BLD04',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'AI & Robotics Explorer: Microcontrollers & Sensors',
    titleAr: 'مستكشف الذكاء الاصطناعي والروبوتات والمتحكمات',
    descEn: 'Explore AI concepts vs traditional automation, prompt engineering, training data bias, microcontrollers (Micro:bit / Arduino), sensors, LEDs, and motors.',
    descAr: 'استكشاف الذكاء الاصطناعي مقابل الأتمتة، هندسة الأوامر Prompts، المتحكمات الدقيقة Micro:bit، الحساسات، والمحركات.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of BLD03 or BLD01. Age 12–14.',
    prerequisiteAr: 'إتمام كورس BLD03 أو BLD01. للأعمار من 12 إلى 14 سنة.',
    levelEn: 'Advanced (Builder 4/4)',
    levelAr: 'متقدم (مسار الباني 4/4)',
    ageBadgeEn: 'Ages 12–14',
    ageBadgeAr: 'من 12 إلى 14 سنة',
    topics: ['AI vs Automation vs Code', 'Dataset Bias & Responsible AI', 'Microcontrollers & Pins', 'Sensors, Motors & Light Actuators', 'Python Vision & Machine Learning'],
    projectsEn: ['Smart Light Automation System', 'Motion Security Alarm Device', 'Reaction Game Tester', 'Simple AI Image Classifier'],
    projectsAr: ['نظام الإضاءة الذكية المباشر Smart Light', 'جهاز إنذار الحركة الأمني Motion Alarm', 'لعبة سرعة رد الفعل Reaction Game', 'مصنف الصور بالذكاء الاصطناعي Classifier'],
    completionStandardEn: 'Build and demonstrate a working hardware/software smart prototype using sensors and Python/Block logic.',
    completionStandardAr: 'بناء نموذج أولي ذكي يعمل بالحساسات والبرمجة وتقديمه في المعرض.'
  },

  // =========================================================================
  // TRACK 4: YOUNG DEVELOPER TRACK (AGES 15–17)
  // =========================================================================
  {
    id: 'cs-python-15-17',
    code: 'DEV01',
    category: 'kids',
    kidsAgeCategory: '15-17',
    titleEn: 'Computer Science & Advanced Python',
    titleAr: 'علوم الحاسب والبرمجة المتقدمة بـ Python',
    descEn: 'Computer Science foundations: data structures (lists, dicts, sets, tuples), OOP, recursion, file handling, complexity intuition, and Git/GitHub.',
    descAr: 'أساسيات علوم الحاسب: هياكل البيانات، البرمجة كائنية التوجه OOP، العودية Recursion، التعامل مع الملفات، والـ Git/GitHub.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'No prior experience required for Age 15–17.',
    prerequisiteAr: 'لا يتطلب معرفة سابقة للأعمار من 15 إلى 17 سنة.',
    levelEn: 'Beginner → Intermediate (Young Dev 1/4)',
    levelAr: 'مبتدئ ← متوسط (الشباب 1/4)',
    ageBadgeEn: 'Ages 15–17',
    ageBadgeAr: 'من 15 إلى 17 سنة',
    topics: ['CS Fundamentals & Algorithmic Thinking', 'Advanced Python Data Structures', 'Object-Oriented Programming (OOP)', 'File Persistence & JSON/CSV', 'Git & GitHub Workflows'],
    projectsEn: ['CLI Study Planner App', 'Inventory Manager System', 'Quiz Platform Engine', 'Mini Banking System CLI'],
    projectsAr: ['تطبيق تنظيم الدراسة CLI Study Planner', 'نظام إدارة المخزون والمبيعات', 'محرك منصة الاختبارات Quiz Engine', 'النظام المصرفي المصغر Mini Banking'],
    completionStandardEn: 'Develop 2 object-oriented Python applications stored in GitHub repositories.',
    completionStandardAr: 'تطوير تطبيقين كائني التوجه بلغة بايثون مرفوعين على GitHub.'
  },
  {
    id: 'web-dev-15-17',
    code: 'DEV02',
    category: 'kids',
    kidsAgeCategory: '15-17',
    titleEn: 'Full Web Development: HTML5, SCSS & JS APIs',
    titleAr: 'تطوير مواقع الويب الكاملة (HTML5/SCSS/JS)',
    descEn: 'Build modern responsive frontend applications: HTML5 semantics, SCSS architecture, Flexbox, Grid, ES6+ JS, DOM APIs, Fetch API, and deployment.',
    descAr: 'بناء تطبيقات الواجهة الأمامية: HTML5، معمارية SCSS، Flexbox & Grid، جافاسكريبت الحديثة، DOM APIs، واستدعاء الـ APIs.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of DEV01 or equivalent programming logic. Age 15–17.',
    prerequisiteAr: 'إتمام كورس DEV01 أو المنطق البرمجي الأساسي. للأعمار من 15 إلى 17 سنة.',
    levelEn: 'Intermediate (Young Dev 2/4)',
    levelAr: 'متوسط (الشباب 2/4)',
    ageBadgeEn: 'Ages 15–17',
    ageBadgeAr: 'من 15 إلى 17 سنة',
    topics: ['HTML5 & SCSS Architecture', 'Responsive CSS Grid & Flexbox', 'JavaScript Async & Fetch API', 'REST API Integration', 'Vercel / Netlify Deployment'],
    projectsEn: ['Developer Portfolio Website', 'Academy Platform Landing Page', 'Movie Explorer & Search App', 'Mini E-Commerce Web Frontend'],
    projectsAr: ['معرض أعمال المطور المحترف Portfolio', 'صفحة هبوط الأكاديمية التفاعلية', 'تطبيق استكشاف وبحث الأفلام بـ API', 'واجهة متجر إلكتروني E-Commerce'],
    completionStandardEn: 'Deploy a responsive web project consuming external REST APIs to Vercel/Netlify with clean Git commit history.',
    completionStandardAr: 'نشر موقع متجاوب مرتبط بـ REST APIs حقيقية على Vercel أو Netlify.'
  },
  {
    id: 'data-ai-foundations-15-17',
    code: 'DEV03',
    category: 'kids',
    kidsAgeCategory: '15-17',
    titleEn: 'Data Science & Machine Learning Foundations',
    titleAr: 'أساسيات علوم البيانات والذكاء الاصطناعي',
    descEn: 'Python data analysis with Pandas & Matplotlib, dataset cleaning, Machine Learning concepts (Classification & Regression), and AI ethics.',
    descAr: 'تحليل البيانات بـ Python باستخدام Pandas & Matplotlib، تنظيف البيانات، مفاهيم التعلم الآلي ML، وأخلاقيات الذكاء الاصطناعي.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of DEV01 or DEV02. Age 15–17.',
    prerequisiteAr: 'إتمام كورس DEV01 أو DEV02. للأعمار من 15 إلى 17 سنة.',
    levelEn: 'Advanced (Young Dev 3/4)',
    levelAr: 'متقدم (الشباب 3/4)',
    ageBadgeEn: 'Ages 15–17',
    ageBadgeAr: 'من 15 إلى 17 سنة',
    topics: ['Python Data Handling & Pandas', 'Data Visualization (Matplotlib)', 'Machine Learning Fundamentals', 'Classification & Regression', 'AI Safety & Privacy'],
    projectsEn: ['Student Performance Analytics Explorer', 'Prediction Model Demo', 'Image Classification Model', 'Sentiment Analysis Mini App'],
    projectsAr: ['محلل أداء الطلاب العلمي Analytics', 'نموذج التنبؤ بالبيانات Prediction', 'نموذج تصنيف الصور Image Classifier', 'تطبيق تحليل المشاعر Sentiment App'],
    completionStandardEn: 'Build and defend a data analysis or machine learning mini-product using real datasets.',
    completionStandardAr: 'بناء نموذج تحليل بيانات أو نموذج ذكاء اصطناعي واختباره بالبيانات الحقيقية.'
  },
  {
    id: 'specialization-capstone-15-17',
    code: 'DEV04',
    category: 'kids',
    kidsAgeCategory: '15-17',
    titleEn: 'Specialization & Graduation Capstone Project',
    titleAr: 'التخصص التقني ومشروع التخرج النهائي',
    descEn: 'Choose a specialized technical track (Web / Mobile / AI / Games / Cyber Security), build a full product, and present at graduation Demo Day.',
    descAr: 'اختيار مسار تخصصي (ويب / موبايل / ذكاء اصطناعي / ألعاب / أمن سيبراني)، بناء منتج كامل، وتقديمه في حفل التخرج.',
    durationEn: '12 Sessions / 24 Hours / 3 Months',
    durationAr: '12 جلسة / 24 ساعة / 3 أشهر',
    sessionsCount: 12,
    weeksCount: 12,
    priceEgp: 3000,
    prerequisiteEn: 'Completion of DEV02 or DEV03. Age 15–17.',
    prerequisiteAr: 'إتمام كورس DEV02 أو DEV03. للأعمار من 15 إلى 17 سنة.',
    levelEn: 'Professional (Young Dev 4/4)',
    levelAr: 'احترافي (الشباب 4/4)',
    ageBadgeEn: 'Ages 15–17',
    ageBadgeAr: 'من 15 إلى 17 سنة',
    topics: ['Full Software Lifecycle & Planning', 'Selected Pathway Mastery', 'Code Review & Testing', 'Portfolio & Case Study Writing', 'Public Presentation Skills'],
    projectsEn: ['Student Portal Web Platform', 'Event Booking Mobile App', 'AI Image Classifier Demo', '2D Adventure Game Capstone'],
    projectsAr: ['منصة الطلاب التفاعلية Student Portal', 'تطبيق حجز الفعاليات بالموبايل', 'نموذج التعرف البصري بالذكاء الاصطناعي', 'لعبة المغامرات ثنائية الأبعاد 2D Capstone'],
    completionStandardEn: 'Successfully build, test, deploy, and present a complete graduation capstone project to the academy panel.',
    completionStandardAr: 'بناء ونشر ومناقشة مشروع التخرج النهائي أمام لجنة الأكاديمية.'
  },

  // =========================================================================
  // ELECTIVES & CLUBS (ALL AGES 8–17)
  // =========================================================================
  {
    id: 'game-dev-club',
    code: 'CLUB01',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'Game Development Club',
    titleAr: 'نادي تطوير الألعاب الرقمية 2D',
    descEn: 'Intensive 8-session game engineering bootcamp covering physics, sprites, level mechanics, sound effects, and publishing a playable 2D game.',
    descAr: 'معسكر تدريبي مكثف في 8 جلسات لبناء وتطوير ألعاب ثنائية الأبعاد كاملة، الفيزياء، المؤثرات ونشر اللعبة.',
    durationEn: '8 Sessions / 16 Hours / 2 Months',
    durationAr: '8 جلسات / 16 ساعة / شهرين',
    sessionsCount: 8,
    weeksCount: 8,
    priceEgp: 2000,
    prerequisiteEn: 'Interest in game creation. Ages 9–17.',
    prerequisiteAr: 'الشغف بتطوير الألعاب. للأعمار من 9 إلى 17 سنة.',
    levelEn: 'All Levels (Elective Club)',
    levelAr: 'جميع المستويات (نادي تخصصي)',
    ageBadgeEn: 'Ages 9–17',
    ageBadgeAr: 'من 9 إلى 17 سنة',
    topics: ['2D Game Engine Basics', 'Sprite Animations & Physics', 'Level Design & Win Conditions', 'Game Audio & Sound FX', 'Publishing Playable Game'],
    projectsEn: ['Complete Playable 2D Arcade Game'],
    projectsAr: ['لعبة أركيد كاملة قابلة للعب والنشر'],
    completionStandardEn: 'Publish a complete 2D playable game with custom assets.',
    completionStandardAr: 'نشر لعبة أركيد كاملة قابلة للعب والتحميل.'
  },
  {
    id: 'ai-kids-club',
    code: 'CLUB02',
    category: 'kids',
    kidsAgeCategory: '12-14',
    titleEn: 'AI for Kids & Teens Club',
    titleAr: 'نادي الذكاء الاصطناعي للأطفال والشباب',
    descEn: 'Hands-on exploration of Machine Learning, dataset training, computer vision demos, prompt engineering, and building an AI mini product.',
    descAr: 'استكشاف عملي لنماذج التعلم الآلي، تدريب البيانات، الرؤية الحاسوبية، هندسة الأوامر Prompts، وبناء منتج ذكاء اصطناعي مصغر.',
    durationEn: '8 Sessions / 16 Hours / 2 Months',
    durationAr: '8 جلسات / 16 ساعة / شهرين',
    sessionsCount: 8,
    weeksCount: 8,
    priceEgp: 2000,
    prerequisiteEn: 'Age 10–17.',
    prerequisiteAr: 'للأعمار من 10 إلى 17 سنة.',
    levelEn: 'All Levels (Elective Club)',
    levelAr: 'جميع المستويات (نادي تخصصي)',
    ageBadgeEn: 'Ages 10–17',
    ageBadgeAr: 'من 10 إلى 17 سنة',
    topics: ['AI Models & Datasets', 'Computer Vision Demonstrations', 'Prompting Discipline', 'AI Ethics & Safety', 'AI Mini Product Creation'],
    projectsEn: ['AI Interactive Mini Product Prototype'],
    projectsAr: ['نموذج تفاعلي لمنتج ذكاء اصطناعي مصغر'],
    completionStandardEn: 'Demonstrate an AI mini-product trained on custom dataset.',
    completionStandardAr: 'تقديم مشروع منتج ذكاء اصطناعي مدرب بالبيانات.'
  },
  {
    id: 'cyber-safety-club',
    code: 'CLUB03',
    category: 'kids',
    kidsAgeCategory: '9-11',
    titleEn: 'Cyber Safety & Digital Ethics Club',
    titleAr: 'نادي الأمان السيبراني والأخلاقيات الرقمية',
    descEn: 'Learn strong password creation, multi-factor authentication concepts, spot phishing scams, privacy settings, and online footprint awareness.',
    descAr: 'تعلم إنشاء كلمات السر القوية، التوثيق المتعدد، اكتشاف محاولات الاحتيال Phishing، إعدادات الخصوصية والأمان الرقمي.',
    durationEn: '6 Sessions / 12 Hours / 1.5 Months',
    durationAr: '6 جلسات / 12 ساعة / شهر ونصف',
    sessionsCount: 6,
    weeksCount: 6,
    priceEgp: 1500,
    prerequisiteEn: 'Age 10–17.',
    prerequisiteAr: 'للأعمار من 10 إلى 17 سنة.',
    levelEn: 'All Levels (Elective Club)',
    levelAr: 'جميع المستويات (نادي تخصصي)',
    ageBadgeEn: 'Ages 10–17',
    ageBadgeAr: 'من 10 إلى 17 سنة',
    topics: ['Strong Password Builder', 'Spotting Phishing & Suspicious Links', 'Social Media Privacy Control', 'Digital Footprint & Ethics', 'Cyber Safety Awareness Project'],
    projectsEn: ['Cyber Safety Interactive Awareness Project'],
    projectsAr: ['مشروع التوعية بالأمان الرقمي والسيبراني'],
    completionStandardEn: 'Pass the cyber safety evaluation and present an online safety guide.',
    completionStandardAr: 'اجتياز تقييم الأمان الرقمي وتقديم دليل التوعية الأمني.'
  }
];
